version: "3.3"

services:
  go-client:
    container_name: api-client
    ports:
      - 3333:3333
    build:
      context: .
    env_file:
      - ./.env
    networks:
      - ammq-network

networks:
  ammq-network:
    external:
      name: ammq-network
